# Introduction 

NumPy is a Python packagae. It stands for "Numerical Python". It is a library consisting of multidimensional array objects and a collection  of routines for processing of array.

#  Operations Using NumPy

Using NumPy, a developer can perform the following operations : 
    
1) Mathematical and logical operations on arrays.

2) Fourier transforms and routines for shape manipulation.

3) Operations related to linear algebra. NumPy has in-built functions for linear algebra fand random number generation.

# What is array ? 

An array is a collection of data stored in a single variable. This is done by allocating equal
memory to for each data. The different datas in the array are denoted by different pointers
(denote the position where the data is stored). Arrays can be of many form 1D,2D,3D and
so on.

![](img/array1.png)

# Array Creation

To create a array there are many different functions like : array(), arrange(), zeros(),
ones(), linspace(), eye(), random(), identity(), rand(), randm(),ranf(),randint()
amd more other functions

## Using  array() function

### One Dimensional array in NumPy

![](img/array3.jpg)

#### Properties 

1) size : number of given data in an array.

2) shape : shape of the array or number of rows, number of column.

in case of 1D array shape = size 

3) ndim : number of dimension here it is 1 

4) dtype : types of elements in the array. 

#### Examples

In [1]:
import numpy as np 

In [2]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [3]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#To check size of the arra we use .size
print(arr1.size)

9


In [5]:
# To check shape of the array we use .shape
print(arr1.shape)

(9,)


In [6]:
# To check dimension of the array we use .ndim
print(arr1.ndim)

1


In [7]:
# To check the data type we use .dtype
print(arr1.dtype)

int32


In [8]:
# float datatype 
arr2 = np.array([1.1,2.5,3,4])
print(arr2.dtype)

float64


In [9]:
# mixing data type 
arr3 = np.array([1,2,3.5,4.9,"hello world"])
arr3

array(['1', '2', '3.5', '4.9', 'hello world'], dtype='<U32')

In [10]:

arr3.dtype

dtype('<U32')

In [11]:
# array creation using list
a = [1,2,3,4,5,6,7,8,9,10]
arr4 = np.array(a)
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Two Dimensional array in NumPy

![](img/array4.png)

#### Properties

1) size : number of given data in an array.

2) shape : shape of the array or number of rows, number of column.

number of rows * number of columlns = size of array

3) ndim : number of dimension here it is 1 

4) dtype : types of elements in the array. 

Remember in sem1 we create matrix using list. matrix is also a two dimensional array in NumPy.

we first take all the elements of the first row using list  and then take all the elements of second row and so on... using list
and then append it in the list 


####  Examples

In [12]:
mat = [[1,2],[3,4]]

for i in range(2):
 for j in range(2):
     print(mat[i][j], end=" ")
 print()

1 2 
3 4 


Now look the samae example using NumPy.

In [13]:
arr5 = np.array([[1,2],[3,4]])
arr5

array([[1, 2],
       [3, 4]])

In [14]:
# to check size of the array we use .size
print(arr5.size)

4


In [15]:
# To check shape of the array we use .shape
print(arr5.shape)

(2, 2)


In [16]:
# to check dimension of array we use .ndim
print(arr5.ndim)

2


In [17]:
# to check data type we use .dtype
print(arr5.dtype)

int32


In [18]:
# to change the data type 
arr6 = np.array(mat, dtype = float)
arr6

array([[1., 2.],
       [3., 4.]])

###  Three Dimensional array in NumPy

![](img/array5.png)

Three dimensional array is not so important topic. 

basically three dimensional array is nothing but two dimensional arrays inside a two dimensional array. or array inside array iside array. 

#### Properties

1) size : number of given data in an array.

2) shape : shape of the array or number of two dimensional arrays,  number of rows, number of column.

number of two dimensional arrays * number of rows * number of columlns = size of array

3) ndim : number of dimension here it is 1 

4) dtype : types of elements in the array. 

#### Examples

In [19]:
arr7 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
arr7

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [20]:
# to check the size of the array we use .size
print(arr7.size)

27


In [21]:
# to check shape of the element we use .shape
print(arr7.shape)

(3, 3, 3)


In [22]:
# to check dimension of the array we use .ndim
print(arr7.ndim)

3


In [23]:
# to check data type of the array we use .dtype
print(arr7.dtype)

int32


## Using arange() function 

syntax : np.arange(start,stop,step)

it is same as range function.

![](img/array6.jpg)

In [24]:
print(np.array(range(1,10,2)))
print(np.arange(1,10,2))

[1 3 5 7 9]
[1 3 5 7 9]


## linespace()

linspace() is used to generate a linea sequence out of the range of number provided.

syntax : np.linspace(start,stop,num = 50, endpoint = True)

by default num = 50

endpoint = True implies we have to consider the endpoint 

here step = $\frac{end - start}{num -1}$

In [25]:
arr8 = np.linspace(1,50,50,dtype = int)
arr8

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [26]:
arr9 = np.linspace(1,50,50, endpoint=False)
arr9

array([ 1.  ,  1.98,  2.96,  3.94,  4.92,  5.9 ,  6.88,  7.86,  8.84,
        9.82, 10.8 , 11.78, 12.76, 13.74, 14.72, 15.7 , 16.68, 17.66,
       18.64, 19.62, 20.6 , 21.58, 22.56, 23.54, 24.52, 25.5 , 26.48,
       27.46, 28.44, 29.42, 30.4 , 31.38, 32.36, 33.34, 34.32, 35.3 ,
       36.28, 37.26, 38.24, 39.22, 40.2 , 41.18, 42.16, 43.14, 44.12,
       45.1 , 46.08, 47.06, 48.04, 49.02])

## geomspace

The geomspace() function is used to get numbers spaced evenly on a log scale (a geometric progression).

Syntax : np.geomspace(start,stop,num = 50,endpoint = True)

In [27]:
arr10 = np.geomspace(1,32,6)
arr10

array([ 1.,  2.,  4.,  8., 16., 32.])

In [28]:
arr11 = np.geomspace(1,32,6, endpoint=False)
arr11

array([ 1.        ,  1.78179744,  3.1748021 ,  5.65685425, 10.0793684 ,
       17.95939277])

## logspace

Syntax : np.logspace(start,stop,num = 50,base = 10)

The logspace() function return numbers spaced evenly on a log scale.
In linear space, the sequence starts at base ** start (base to the power of start) and ends with base ** stop.

In [29]:
arr12 = np.logspace(1,5,5)
arr12

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05])

In [30]:
arr13 = np.logspace(1,5,5,base= 2)
arr13

array([ 2.,  4.,  8., 16., 32.])

##  Dynamic Functions For Array Creations

### zeros 

Syntax : np.zeros(shape,dtype=float by default): array filled with zero of the given shape

For two or three dimensional arrays we use tuple or list as shape 

In [31]:
# one dimensional array creations using .zeros()
arr14 = np.zeros(10)
arr14

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
# change the data type 
print(np.zeros(10, int))

[0 0 0 0 0 0 0 0 0 0]


In [33]:
# two dimensional array creations using .zeros()
arr15 = np.zeros((5,5))
arr15

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
arr16 = np.zeros([10,10],int)
arr16

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

###  ones

Syntax : np.ones(shape,dtype=float by default): array filled with one of the given 

similarly we use tuple or list for two or three dimensional array.

In [35]:
#  one dimensional array creations usin .ones()
arr17 = np.ones(5)
arr17

array([1., 1., 1., 1., 1.])

In [36]:
# two dimensional array creations using .ones()
arr18 = np.ones([3,2],int)
arr18

array([[1, 1],
       [1, 1],
       [1, 1]])

### full

Syntax : >np.full(shape, value to be filled, dtype= By default the dtype of the value given): An array

similarly we use list or tuple for multidimensioal array.

In [37]:
# one dimensional array creation using .full()
arr19 = np.full(5,4,int)
arr19

array([4, 4, 4, 4, 4])

In [38]:
# two dimensional array creations using .full()
arr20 = np.full((3,3), 5)
arr20

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

### fill

Syntax : array_name.fill(value)
    
using fill() we can fill a existing array.


In [39]:
arr20.fill(10)
arr20

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

### eye

return array filled with 0 except kth diagonal whose values are equal to 1

Syntax : np.eye(shape,dtype, k)

In [40]:
# when we use single input as shape then it make a squre matrix
# by default it makes 1 along principle diagonal 
arr21 = np.eye(5)
arr21

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
# creating array with different shapes
arr22 = np.eye(3,5)
arr22

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [42]:
print("when k is positve then it makes 1 in the upper diagonal.")
arr23 = np.eye(5,9,k = 1)
arr23


when k is positve then it makes 1 in the upper diagonal.


array([[0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.]])

In [43]:
print("when k is negative then it makes 1 in the lower diagonal.")
arr24 = np.eye(5,9, k = -1)
arr24

when k is negative then it makes 1 in the lower diagonal.


array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.]])

### identity

identity() is same as eye(). identity is only applicable for square matrix.

Syntax : np.identity(shape,dtype, k)

In [44]:
arr25 = np.identity(4)
arr25


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### astype

astype() is used to changed data type 

Syntax : new-array = old_array.astype(dtype)


In [45]:
arr26 = arr25.astype(int)
arr26

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

### reshaping  of array

array can be reshped by using reshape function or resize function

#### reshape function 

reshape function  do not change the array data. 

syntax is np.reshape(array, shape, order) or we may use array.reshape()

In [46]:
arr27 = np.arange(1,25)
print(arr27)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [47]:
print(arr27.reshape((4,6)))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [48]:
print(np.reshape(arr27,(6,4)))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


#### resize function 

resize function can change the data of the array

if new array is larger than current array then new array can be filled with repeated
copies of array. syntax is np.resize(array, shape)


In [49]:
arr28 = np.arange(1,29)
print(arr28)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28]


In [50]:
print(np.resize(arr28,(4,7)))

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]]


In [51]:
print(np.resize(arr28,(4,9)))

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]
 [28  1  2  3  4  5  6  7  8]]


### array flattening

there are basically two method i know

1 flatten method

2 ravels function

####  flatten method 

by this method we get copy of a multi dimensional
array in one dimensional array.

syntax ndarray.flatten(order) by default order is 'c'. there are mainly 4 types

1 C : flatten the array in row

2 A : flatten in column-major order if a is Fortran contiguous in memory, row-major order otherwise.

3 F : flatten the array in column

4 K : flatten a in the order the elements occur in memory.

usually use C or F


In [52]:
arr29 = np.arange(1,10).reshape(3,3)
print(arr29)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
print(arr29.flatten())
# by default order is C

[1 2 3 4 5 6 7 8 9]


In [54]:
print(arr29)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [55]:
print(arr29.flatten(order = "F"))

[1 4 7 2 5 8 3 6 9]


In [56]:
arr30 = arr29.flatten()
arr30[6] = 17
print(arr30)
print(arr29)
print(arr29.flatten())
# hence prove that flatten function do not change the original array it makes a copy of the array.

[ 1  2  3  4  5  6 17  8  9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


#### ravel function 

this is almost same as flatten method main difference is it is
just only view of the original array it is needed but in flatten method it
always make a copy of original array

flatten() is a method not a function that's why we dont write np.flatten()
flatten is a method of a nd array but ravar is a function  of a numpy
syntax: np.ravel(array, order)


In [57]:
arr31 = np.arange(1,10).reshape(3,3)
print(arr31)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [58]:
print(np.ravel(arr31))

[1 2 3 4 5 6 7 8 9]


In [59]:
print(np.ravel(arr31,order = "F"))

[1 4 7 2 5 8 3 6 9]


In [60]:
arr32 = np.ravel(arr31)
arr32[5] = 18
print(arr31)
print(arr31.ravel())
# hence prove that ravel can make change in the original array and it only the view of the array.

[[ 1  2  3]
 [ 4  5 18]
 [ 7  8  9]]
[ 1  2  3  4  5 18  7  8  9]


### shuffle an array

there are mainly two function transpose() and swapaxis()



#### transpose 

this transpose() is rearrange the dimension of an array

syntax : np.transpose(array, axes = None) default value of axes is None.

for axes = None it will transpose the array otherwise it will rearrange the array
based on that values.

it dont coppy the data.

for one dimensional array we generally dont use this function because it do not change the
order of the array

for two dimensional array the number of axes are two first is 0 that is along the column
and second is 1 that is along row. there are only two combination available (0,1),(1,0)
for (0,1) it is the same order and for (1,0) it is reverse order which refers the transpose or
 default value
 note that transpose is also a method so we use array.transpose() or we may use array.T
 for transpose

In [61]:
arr33 = np.arange(1,10).reshape(3,3)
print(arr33)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [62]:
print(np.transpose(arr33))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [63]:
print(np.transpose(arr33,axes = (0,1)))


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [64]:
print(arr33.transpose((1,0)))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [65]:
print(arr33.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


#### swapaxes 

to change any two axes of an array we may use swapaxes() fuction
syntax : np.swapaxes(array, axes1,axes2)
here 0,1 and 1,0 are same as this swap the two axes 

In [66]:
arr34 = np.arange(1,25).reshape(4,6)
print(arr34)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [67]:
print(np.swapaxes(arr34,0,1))

[[ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]
 [ 6 12 18 24]]


In [68]:
print(np.swapaxes(arr34,1,0))

[[ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]
 [ 6 12 18 24]]


### stacking the two arrays

there are  two functions to join arrays
hstack() and vstack()

#### vstack

this function combine arrays vertically

syntax : np.vstack(arrays )
    
in 2D array concatenation vstack() is same as axis as 0

In [69]:
arr35 = np.array([1,2,3,4,5,6])
arr36 = np.array([7,8,9])
arr37 = np.array([10,11,12])
print(arr35)
print(arr36)
print(arr37)

[1 2 3 4 5 6]
[7 8 9]
[10 11 12]


for 1D array of unequal elements or shapes it show a error
actually in vstack() 1D array is treated as a matrix or 2D array with order (1,n)
since vstack() is operated along axis 0 so it check the index along the other axis


In [70]:
print(np.vstack((arr35,arr36)))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 6 and the array at index 1 has size 3

In [ ]:
print(np.vstack((arr36,arr37)))

in 2D array vstack() is same as concatenate with axis 0
 vstack() behave different in 1D array but in 2D or other arrays it behave like as concatenate """


In [71]:
arr38 = np.arange(1,5).reshape(2,2)
arr39 = np.arange(5,9).reshape(2,2)
print(arr38)
print(arr39)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [72]:
print(np.vstack((arr38,arr39)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### hstack

this function combines arrays in horizontally

syntax np.hstack(arrays)

here axis is 1

in 1D it behaves different but in 2D or other arrays it behaves like concatenate with axis 1


In [73]:
arr40 = np.arange(1,5)
arr41 = np.arange(5,9)
print(arr40)
print(arr41)

[1 2 3 4]
[5 6 7 8]


In [74]:
print(np.hstack((arr40,arr41)))

[1 2 3 4 5 6 7 8]


In [75]:
arr42 = np.arange(1,5).reshape(2,2)
arr43 = np.arange(5,9).reshape(2,2)
print(arr42)
print(arr43)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [76]:
print(np.hstack((arr42,arr43)))

[[1 2 5 6]
 [3 4 7 8]]


# Array Indexing and Slicing

## 1D array indexing

![](img/array7.png)

In [77]:
arr44 = np.arange(1,6)
print(arr44)
# array indexing is similar to list indexing
print(arr44[0])
print(arr44[4])
print(arr44[-1])
print(arr44[-4])

[1 2 3 4 5]
1
5
5
2


## 2D array indexing

 for 2D indexing we use 2[] for first one we use row number and
for second one we use column number. for row number index of first row is 0 and so on...
and for column index of first column is 0 and so  on......
here we also use negative indexing
for printing only a single row we use single[] and use index number of the row

![](img/array8.png)

In [78]:
arr45 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr45)
print(arr45[0]) # for printing first row 
print(arr45[1]) # for printing second row 
# there are no method to print columns using indexing. but later we do this using slicing.


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[4 5 6]


In [79]:
print(arr45[0,0]) 
print(arr45[1,1])
print(arr45[-1,-1])

1
5
9


##  1D array slicing

slicing operation  in array. to retrieve a collection of values we use slicing method

syntax of the 1D array slicing is array_name[start : stop : step]
here start is starting index, stop is stopping index and step is difference between index
and here stopping index is excluded and here default step is 1 and default start is starting index
and default stopping index is stopping index

In [80]:
print(arr44)

[1 2 3 4 5]


In [81]:
print(arr44[::]) # to print full array

[1 2 3 4 5]


In [82]:
print(arr44[0:3])

[1 2 3]


In [83]:
print(arr44[0:5:2]) 

[1 3 5]


In [84]:
print(arr44[2:])

[3 4 5]


In [85]:
print(arr44[:4])

[1 2 3 4]


## 2D array slicing

syntax is array_name[strat:end:step, start: end :step]
here first part is for row and second part is for column


In [86]:
print(arr45)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [87]:
print(arr45[::]) # to print full array

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [88]:
# to print rows 
print(arr45[0:1])
print(arr45[1:2])
print(arr45[2:3])

[[1 2 3]]
[[4 5 6]]
[[7 8 9]]


In [89]:
# to print columns
print(arr45[:,0])
print(arr45[:,1])
print(arr45[:,2])
# to print first two columns 
print(arr45[:,0:2])

[1 4 7]
[2 5 8]
[3 6 9]
[[1 2]
 [4 5]
 [7 8]]


In [90]:
print(arr45)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [91]:
# to print first two elements of first row.
print(arr45[:1,:2])

[[1 2]]


In [92]:
# to print last two elements means 8,9
print(arr45[2:,1:])

[[8 9]]


In [93]:
# to print first 4 square matrix elemlents mens 1,2,4,5
print(arr45[:2,:2])

[[1 2]
 [4 5]]


In [94]:
# to print last 4 square elements means 5,6,8,9
print(arr45[1:,1:])

[[5 6]
 [8 9]]


thats about array indexing and slilcing...

## Arithmetic  operation : 

arithmetic operations are basically two types one is by using scalars such that multiplying
or dividing by scalars and other one is array operations such that multiplying two arrays and more


### scalar operations

In [95]:
arr46 = np.arange(1,6)
print(arr46)
# to add or subtract or multiplying or dividing  by  scalar to every element of the array
print(arr46 + 2)
print(arr46 -1)
print(arr46*5)
print(arr46/4)
print(arr46**2)

[1 2 3 4 5]
[3 4 5 6 7]
[0 1 2 3 4]
[ 5 10 15 20 25]
[0.25 0.5  0.75 1.   1.25]
[ 1  4  9 16 25]


to add or subtract or other mathematical operations is same in nd array
print(i1)

In [96]:
arr47 = np.array([[1,2],[3,4]])
print(arr47)
print(arr47+2)
print(arr47-1)
print(arr47*2)
print(arr47/2)
print(arr47**2)

[[1 2]
 [3 4]]
[[3 4]
 [5 6]]
[[0 1]
 [2 3]]
[[2 4]
 [6 8]]
[[0.5 1. ]
 [1.5 2. ]]
[[ 1  4]
 [ 9 16]]


### arithmetic operations with arrays

In [97]:
# for 1D array
arr48 = np.arange(1,6)
arr49 = np.arange(6,11)
print(arr48)
print(arr49)
print(arr48+arr49)
print(arr48-arr49)
print(arr48*arr49)
print(arr48/arr49)
print(arr48**arr49)

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[      1     128    6561  262144 9765625]


In [98]:
arr50 = np.arange(1,5).reshape(2,2)
print(arr50)
arr51 = np.arange(5,9).reshape(2,2)
print(arr51)
#for addition, subtraction, division, multiplication  same index will be operated
print(arr50+arr51)
print(arr50-arr51)
print(arr50*arr51)# note that this multiplication is not same as matrix multiplication
print(arr50/arr51)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


instead of using operators we may use functions also given below

a+b =  np.add(a,b)

a-b =  np.subtract(a,b)

a*b = np.multiply(a,b)

a/b = np.divide(a,b)

a%b = np.mod(a,b)

a**b = np.power(a,b)

in arithmetic operations we cannot use different shape or size of arrays.

now questions is how a scalar is operated with a array?

this is because of broadcasting of arry.

using broadcasting we use arithmetic operations in two different shapes or sized array.
broadcasting actually make both array in same shapes and sized and then use arithmetic operations
like if we add 5 with a array of 6 elements then by broadcasting 5 is treated as a arrays of 5
and shape of this array is 6 and then do the arithmetic operations.
but note that numpy do not stretched or broadcast the array, numpy just do the computation without
stretching the array or copping the values.

###  broadcasting of array

In [99]:
arr52 = np.array([1,2,3])
arr53 = np.array([4,5,6,7])
print(arr52)
print(arr53)

[1 2 3]
[4 5 6 7]


there are some rules of broadcasting or conditions of broadcasting

rule 1: size of each dimension should be same

rule 2: size of one of the dimension should be 1

these are the two main rules but in calculating we follow some other rules also

rule 3 : if the two arrays differ in their nunber of dimensions, the shape of the one with fewer
dimension is padded with ones on its left leading side.

rule 4 : if the shape of the two arrays does not match in any dimension, the array with shape
equal to 1 in that dimension is streatched to match the other shape.

rule 5 : if in any dimension the sizes disagree and neither equal to 1 an error is raised.


In [100]:
print(arr52+arr53)# here we get error because we do not follow rule no 5.

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [103]:
arr54  = np.arange(6).reshape(2,3)
arr55 = np.arange(6).reshape(3,2)
print(arr54)
print(arr55)

[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


here according to rule no 1 size of the one dimension is same and that is 3 but other is not same.


so according to rule 3 we add 1 in left to fewer dimension. so the n1  array become size of 1,3


note that the number of column must be equal then rule number 3 is applicable

In [104]:
print(arr54+arr55) #print(q1+ n1)# here we get error because the number of column is not equal

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [105]:
arr56 = np.arange(1,7).reshape(3,2)
arr57 = np.arange(1,5).reshape(2,2)
print(arr56)
print(arr57)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]


In [106]:
print(arr56+arr57)# here we get error because here column number is same but row number is not same or any one of the dimension is not 1

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [107]:
arr58 = np.arange(1,4).reshape(3,1)
arr59 = np.arange(4,7).reshape(1,3)
print(arr58)
print(arr59)
print(arr58+arr59)# here both the array will be stretched according to rule no 3.


[[1]
 [2]
 [3]]
[[4 5 6]]
[[5 6 7]
 [6 7 8]
 [7 8 9]]
