# Introduction 

## What is matrices ?  

Matrices are 2-D array with different shapes. 

we can create matrix using numppy array or matrix class 

I dont recomend to use matrix class in future. 

## Creating Matrices 

Since matrix is a 2d array, we can create matrix using array or matrix class 

### Using Numpy Array 

In [1]:
import numpy as np 
matrix1 = np.array([[1,2],[3,4]])
print(matrix1)

[[1 2]
 [3 4]]


In [2]:
matrix2 = np.arange(9).reshape(3,3)
print(matrix2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Using matrix class 

In [3]:
matrix3 = np.matrix([[1,2],[3,4]])
print(matrix3)

[[1 2]
 [3 4]]


In [4]:
matrix4 = np.matrix("1 2;3 4") #here every space means new elements and ; means new row 
print(matrix4) 

[[1 2]
 [3 4]]


## Matrix Operations 

### Using array method 

In [5]:
matrix5  = np.arange(9).reshape(3,3)
matrix6 = np.array([[9,10,11],[12,13,14],[15,16,17]])
print(matrix5)
print(matrix6)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


#### Addition 

In [6]:
print(matrix5+matrix6)
# or 
print(np.add(matrix5,matrix6))

[[ 9 11 13]
 [15 17 19]
 [21 23 25]]
[[ 9 11 13]
 [15 17 19]
 [21 23 25]]


#### Substraction 

In [7]:
matrix7  = np.arange(9).reshape(3,3)
matrix8 = np.array([[9,10,11],[12,13,14],[15,16,17]])
print(matrix7)
print(matrix8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [8]:
print(matrix8-matrix7)
#or 
print(np.subtract(matrix7,matrix8))
# order is important 

[[9 9 9]
 [9 9 9]
 [9 9 9]]
[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]


#### Multiplication 

In [9]:
matrix9  = np.arange(9).reshape(3,3)
matrix10 = np.array([[9,10,11],[12,13,14],[15,16,17]])
print(matrix9)
print(matrix10)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [10]:
print(matrix9*matrix10) # this is array multiplicaion not matrix multiplication 
print(np.multiply(matrix10,matrix9)) # order is not important in array multiplilation 
print(matrix9.dot(matrix10))
print(matrix10.dot(matrix9)) # order is important 

[[  0  10  22]
 [ 36  52  70]
 [ 90 112 136]]
[[  0  10  22]
 [ 36  52  70]
 [ 90 112 136]]
[[ 42  45  48]
 [150 162 174]
 [258 279 300]]
[[ 96 126 156]
 [123 162 201]
 [150 198 246]]


####  Transpose 

In [11]:
matrix11 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix11)
print(np.transpose(matrix11))
# or 
print(matrix11.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Using matrix class

#### Addition 

In [12]:
matrix12 = np.array([[1,2],[3,4]])
matrix13 = np.array([[5,6],[7,8]])
print(matrix12)
print(matrix13)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [13]:
print(matrix12 + matrix13)
#or 
print(np.add(matrix12,matrix13))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


#### Substraction

In [14]:
matrix14 = np.matrix([[1,2],[3,4]])
matrix15 = np.matrix([[5,6],[7,8]])
print(matrix14)
print(matrix15)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [15]:
print(matrix15-matrix14)
# or 
print(np.subtract(matrix14,matrix15))

[[4 4]
 [4 4]]
[[-4 -4]
 [-4 -4]]


#### Multiplication 

In [16]:
matrix16 = np.matrix([[1,2],[3,4]])
matrix17 = np.matrix([[5,6],[7,8]])
print(matrix16)
print(matrix17)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [17]:
print(matrix16*matrix17)# this is the advantage of using matrix class 
# or 
print(matrix16.dot(matrix17))
print(np.multiply(matrix16,matrix17))# this is array multiplication 

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]


#### Transpose 

In [18]:
matrix18 = np.matrix(np.arange(9).reshape(3,3))
print(matrix18)
print(np.transpose(matrix18))
# or 
print(matrix18.T)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


#### Power of a matrix

In [19]:
matrix19 = np.array([[1,2],[3,4]])
print(matrix19)

[[1 2]
 [3 4]]


In [20]:
# power of a array 
print(np.power(matrix19,2))

[[ 1  4]
 [ 9 16]]


In [21]:
# matrix power 
print(np.linalg.matrix_power(matrix19,2))

[[ 7 10]
 [15 22]]


## Aggregate function 

np.sum(array,dtype) : sums all the element of the array

np.prod(array,dtype) : product all the element of the array

np.mean(array,dtype) : mean of the  elemenmts of the array

np.std(array,dtype) : standard deviation of the elements of the array

np.var(array,dtype) : variance of the elements of the array

np.min(array,dtype) : mininum of the elements of the array

np.max(array,dtype) : maximum of the elements of the array

np.argmin(array,dtype,axis) index of the minimum of the elemlents of the array ,axis = 0 (column),axis = 1 (row)

np.argmax(array,dtype,axis) : index of the maximum of the elements of the array ,axis = 0 (column), axis = 1 (row)



In [23]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [24]:
#sum
print(np.sum(arr1))

45


In [25]:
#product
print(np.prod(arr1))

362880


In [26]:
#mean
print(np.mean(arr1))

5.0


In [30]:
#standard deviation 
print(np.std(arr1))

2.581988897471611


In [28]:
#variance
print(np.var(arr1))

6.666666666666667


In [31]:
#minimum
print(np.min(arr1))

1


In [32]:
#maximum
print(np.max(arr1))

9


In [33]:
#index of minimum
print(np.argmin(arr1))

0


In [34]:
#index of the maximum
print(np.argmax(arr1))

8
