# Introduction 

In mathematics, Gaussian elimination, also known as row reduction, is an algorithm for solving systems of linear equations. It consists of a sequence of operations performed on the corresponding matrix of coefficients. This method can also be used to compute the rank of a matrix, the determinant of a square matrix, and the inverse of an invertible matrix. The method is named after Carl Friedrich Gauss (1777–1855) although some special cases of the method—albeit presented without proof—were known to Chinese mathematicians as early as circa 179 CE.

## Solving Linear Equations: Gaussian Elimination with pivoting 

Gauss elemination is a method to solve a system of linear equations. 

Let us consider a system of linear equations.

$$2x+y-z = 8$$
$$-3x-y+2z = -11$$
$$-2x +y+ 2z =-3 $$

So, we now have to perform row operations such that we make it upper triangular matrix using
row operations using a pivot.

\begin{bmatrix}
2 & 1 & -1 & 8 \\
-3 & -1  & 2 & -11 \\
-2 & 1 & 2 & -3\\
\end{bmatrix}


$$R_2 \rightarrow R_2 + \frac{3}{2}R_1$$ 

$$R_3 \rightarrow R_3 +R_1$$

\begin{bmatrix}
2 & 1 & -1 & 8\\
0 & \frac{1}{2} & \frac{1}{2} & 1 \\
0 & 2 & 1 & 5
\end{bmatrix}

$$R_3 \rightarrow R_ 3 -4\times R_2$$

\begin{bmatrix}
2 & 1 &-1 &8\\
0 & \frac{1}{2} & \frac{1}{2} & 1\\
0 & 0 & -1 & 1\\
\end{bmatrix}\\

The matrix is now in echelon form (also called triangular form)
 

back substitution  :

$$-z = 1 $$

$$\implies z = -1$$

puttng the value of z 

$$\frac{1}{2}y -\frac{1}{2} = 1$$

$$\implies y = 3$$

putting the values of y,z

$$2x + 3 +1 = 8$$

$$\implies x = 2 $$

## Code : 

In [1]:
import numpy as np 
# augmented matrix 
arr = np.array([[2,1,-1,8],[-3,-1,2,-11],[-2,1,2,-3]],dtype = float)
print(arr)

[[  2.   1.  -1.   8.]
 [ -3.  -1.   2. -11.]
 [ -2.   1.   2.  -3.]]


In [2]:
row = 3 
col = 4 
sol = np.zeros(row)

In [3]:
# determine constant 
for i in range(1,row):
    for j in range(i,row):
        constant = arr[j][i-1]/arr[i-1][i-1]
        for k in range(col):
            arr[j][k] = arr[j][k] -constant*arr[i-1][k] 
print(arr)

[[ 2.   1.  -1.   8. ]
 [ 0.   0.5  0.5  1. ]
 [ 0.   0.  -1.   1. ]]


In [4]:
# back substituion 
for i in range(row-1,-1,-1):
    sol[i] = arr[i][col-1] # store the constatnts in the sol
    for j in range(i+1,col-1):
        sol[i] = sol[i] - arr[i][j]*sol[j]
    sol[i] = sol[i]/arr[i][i]
print(sol)

[ 2.  3. -1.]


In [5]:
# determinant
det = 1
for i in range(row):
    det = det*arr[i][i]
print(f"determinant is {det}")

determinant is -1.0


now we solve the same problem with linalg module  

## Linalg module :

In [6]:
arr1 = np.array([[2,1,-1],[-3,-1,2],[-2,1,2]],dtype = float)
arr2 = np.array([8,-11,-3])
print(arr1)
print(arr2)

[[ 2.  1. -1.]
 [-3. -1.  2.]
 [-2.  1.  2.]]
[  8 -11  -3]


In [7]:
solution = np.linalg.solve(arr1,arr2)
print(solution)

[ 2.  3. -1.]


In [8]:
x,y,z = solution
print(f"solutions of system of linear equations are x = {x},y = {y},z = {z}")

solutions of system of linear equations are x = 2.0000000000000004,y = 2.9999999999999996,z = -0.9999999999999991


In [9]:
# determinant 
print(np.linalg.det(arr1))

-0.9999999999999996


In [10]:
# eigen values and eigen vectors 
eig_value, eig_vec = np.linalg.eig(arr1)
print(f"eigen values are {eig_value} \n eigen vectors are {eig_vec}")

eigen values are [ 3.21431974  0.46081113 -0.67513087] 
 eigen vectors are [[-0.22113623  0.58085736  0.46692616]
 [ 0.54213889 -0.08443477 -0.65511222]
 [ 0.81066898  0.80961441  0.59397638]]


In [11]:
# diagonalization of the matrix
eig_values = np.linalg.eigvals(arr1)
print(eig_values)
diag_matrix = np.zeros((3,3))
for i in  range(len(eig_values)):
    diag_matrix[i][i] += eig_values[i]
print(diag_matrix)

[ 3.21431974  0.46081113 -0.67513087]
[[ 3.21431974  0.          0.        ]
 [ 0.          0.46081113  0.        ]
 [ 0.          0.         -0.67513087]]
